name: Build and lint
on:
  #push: 
  #  branches:
  #    - main
  pull_request:
    branches:
      - main
jobs: 
  prod-setup-ci:
    name: Build and test project
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-v: [14, 16, 18]
    steps:
      - name: Setup checkout
        uses: actions/checkout@main
      
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
      
      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest
          run_install: false

      - name: Set output for pnpm cache store
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      
      - name: Setup cache
        uses: actions/cache@main
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
        
      - name: Setup depends and out PNPM version
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Archive /dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-project
          path: dist
          retention-days: 2