name: build-lint-action
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  build-linux:
    environment: prod-env
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-v: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
      - run: pnpm -v
