name: npm-publish
on: 
  release:
      types: [published, created, released]
      branches: 
        - main
jobs: 
  runs-on: ubuntu-latest
  steps:
    - name: Setup checkout
      uses: actions/checkout@main

    - name: Setup Node.js
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node }}

    - name: Publish
      run: echo 'pub npm'