name: publish-npm
on:
  release:
    types: 
      - published
      - created
      - released
      - edited
    branches:
      - main
  push:
    branches:
      - main
jobs:
  publish-npm:
    name: Publish project on NPM
    runs-on: ubuntu-latest
    steps:
      - name: Setup release label  
        uses: actions-ecosystem/action-release-label@main
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - name: Setup get latest tag  
        uses: actions-ecosystem/action-get-latest-tag@main
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
    
      - name: Setup checkout
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest
          run_install: false
      
      - run: pnpm i 
      - run: pnpm build

      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - run: echo ${{ steps.get-latest-tag.outputs.tag }}

      #- run: pnpm version from-git -git-tag-version -allow-same-version -force
      
      #- run: pnpm publish --no-git-checks
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 