name: publish-to-npm
on:
  release:
    types:
      - created
jobs:
  publish-package:
    name: Publish project on NPM
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest
          run_install: false

      - name: Set package.json version
        run: |
          pnpm version ${{ github.ref_name }} --git-tag-version --allow-same-version --force
      
      - name: Install depends
        run: pnpm i

      - name: Build project
        run: pnpm build

      - name: Auth in GIT
        run: |
           git config user.name "GitHub Actions Bot"
           git config user.email "<>"

      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
