name: publish-npm
on:
  release:
    types: [published, created, released, edited]
    branches: [main]
jobs:
  publish-npm:
    name: Publish project on NPM
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest
          run_install: false
      
      - run: pnpm i 
      - run: pnpm build

      - run: pnpm version patch -git-tag-version false
      
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 