name: publish-npm
on:
  push: 
    branches: [main]
  release:
    types: [published, created, released]
    branches: [main]
jobs:
  publish-npm:
    if: ${{ github.ref_name == 'main' }}
    name: Publish project on NPM
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest
          run_install: false
      
      - run: pnpm i 
      - run: pnpm build
      
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 